(function(a,d,w){function l(a){for(var b={},f,q,c=0;c<a.length;c++)q=a[c],f=q.r+q.s+q.m,q.c&&(b[f]||(b[f]=[]),b[f].push(a[c]));return b}function k(a){for(var b=1;b<arguments.length;b++){var f=arguments[b];try{if(f.isSupported)return f.send(a)}catch(q){}}}function u(){for(var a=0;a<e.length;a++)e[a]();m.length&&k(l(m.splice(0,m.length)),M,L,G);F=I=0}function A(y,b,f){f=f||{};0===f.bf&&n.isBF||(y={r:f.r||n.rid,s:f.s||a.ue_sid,m:f.m||a.ue_mid,mkt:f.mkt||a.ue_mkt,sn:f.sn||a.ue_sn,c:b,d:y,t:f.t||n.d(),
cs:f.c&&a.ue_qsl},f.b?k(l([y]),M,G):f.nb?k(l([y]),M,L,G):f.img||K[b]?k(l([y]),G):f.ff?(m.push(y),u()):f.n?(m.push(y),0===N?u():F||(F=d.setTimeout(u,N))):(m.push(y),I||(I=d.setTimeout(u,J))))}function g(a,b,f){H++;H==h&&A({m:"Max number of Forester Logs exceeded",f:"forester-client.js",logLevel:"ERROR"},d.ue_err_chan||"jserr");(H<h||f&&f.il)&&A(a,b,f)}function v(){if(!D){for(var a=0;a<b.length;a++)b[a]();for(a=0;a<e.length;a++)e[a]();k(l(m.splice(0,m.length)),M,G);D=!0}}var x={};(function(){function a(f){return 10>
f?"0"+f:f}function b(a){q.lastIndex=0;return q.test(a)?'"'+a.replace(q,function(a){var f=B[a];return"string"===typeof f?f:"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)})+'"':'"'+a+'"'}function f(a,q){var y,B,d,n,h=c,D,E=q[a];E&&"object"===typeof E&&"function"===typeof E.toJSON&&(E=E.toJSON(a));"function"===typeof e&&(E=e.call(q,a,E));switch(typeof E){case "string":return b(E);case "number":return isFinite(E)?String(E):"null";case "boolean":case "null":return String(E);case "object":if(!E)return"null";
c+=m;D=[];if("[object Array]"===Object.prototype.toString.apply(E)){n=E.length;for(y=0;y<n;y+=1)D[y]=f(y,E)||"null";d=0===D.length?"[]":c?"[\n"+c+D.join(",\n"+c)+"\n"+h+"]":"["+D.join(",")+"]";c=h;return d}if(e&&"object"===typeof e)for(n=e.length,y=0;y<n;y+=1)"string"===typeof e[y]&&(B=e[y],(d=f(B,E))&&D.push(b(B)+(c?": ":":")+d));else for(B in E)Object.prototype.hasOwnProperty.call(E,B)&&(d=f(B,E))&&D.push(b(B)+(c?": ":":")+d);d=0===D.length?"{}":c?"{\n"+c+D.join(",\n"+c)+"\n"+h+"}":"{"+D.join(",")+
"}";c=h;return d}}"function"!==typeof Date.prototype.toJSON&&(Date.prototype.toJSON=function(f){return isFinite(this.valueOf())?this.getUTCFullYear()+"-"+a(this.getUTCMonth()+1)+"-"+a(this.getUTCDate())+"T"+a(this.getUTCHours())+":"+a(this.getUTCMinutes())+":"+a(this.getUTCSeconds())+"Z":null},String.prototype.toJSON=Number.prototype.toJSON=Boolean.prototype.toJSON=function(a){return this.valueOf()});var q=/[\\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,
c,m,B={"\b":"\\b","\t":"\\t","\n":"\\n","\f":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"},e;"function"!==typeof x.stringify&&(x.stringify=function(a,q,y){var B;m=c="";if("number"===typeof y)for(B=0;B<y;B+=1)m+=" ";else"string"===typeof y&&(m=y);if((e=q)&&"function"!==typeof q&&("object"!==typeof q||"number"!==typeof q.length))throw Error("JSON.stringify");return f("",{"":a})})})();var r=function(){function a(b,f){if(null==b)return f.push("!n");if("number"===typeof b)return f.push("!"+b);if("string"===
typeof b)return"\\"==b[b.length-1]?f.push("'"+b.replace(/'/g,"\\'")+"u005C'"):f.push("'"+b.replace(/'/g,"\\'")+"'");if("boolean"===typeof b)return f.push(b?"!t":"!f");if(b instanceof Array){f.push("*");for(var q=0;q<b.length;q++)a(b[q],f);return f.push(")")}if("object"==typeof b){f.push("(");for(q in b)b.hasOwnProperty(q)&&(f.push(q),a(b[q],f));return f.push(")")}return f.push("!n")}return{stringify:function(b){var f=[];a(b,f);return f.join("")}}}(),p=a.ue_qsl||2E3,h=1E3,z=function(){},t=d.JSON&&
d.JSON.stringify||x&&x.stringify,C=r.stringify,n=a.ue||{},r=a.uet||z;(a.uet||z)("bb","ue_frst_v2",{wb:1});var c="//"+a.ue_furl+"/1/batch/1/OE/",m=[],b=[],e=[],D=!1,F,I,N=void 0===a.ue_hpfi?1E3:a.ue_hpfi,J=void 0===a.ue_lpfi?1E4:a.ue_lpfi,K={"scheduled-delivery":1},H=0,L=function(){function y(){if(d.XDomainRequest){var a=new XDomainRequest;a.onerror=z;a.ontimeout=z;a.onprogress=z;a.onload=z;a.timeout=0;return a}if(d.XMLHttpRequest){a=new XMLHttpRequest;if(!("withCredentials"in a))throw"";return a}if(d.ActiveXObject){for(var y=
0;y<f.length&&!a;y++)try{a=new ActiveXObject(f[y]),f=[f[y]]}catch(b){}return a}}function b(f){for(var y=[],c=f[0]||{},B=0;B<f.length;B++){var m={};m[f[B].c]=f[B].d;y.push(m)}return{rid:c.r||n.rid,sid:c.s||a.ue_sid,mid:c.m||a.ue_mid,mkt:c.mkt||a.ue_mkt,sn:c.sn||a.ue_sn,reqs:y}}var f="MSXML2.XMLHTTP.6.0 MSXML2.XMLHTTP.5.0 MSXML2.XMLHTTP.4.0 MSXML2.XMLHTTP.3.0 MSXML2.XMLHTTP Microsoft.XMLHTTP".split(" ");return{send:function(a){for(var f in a)if(a.hasOwnProperty(f)&&a[f].length){var m=b(a[f]),B=y();
if(!B)throw"";B.open("POST",c,!0);B.setRequestHeader&&B.setRequestHeader("Content-type","text/plain");B.send(t(m))}},buildPOSTBodyLog:b,isSupported:!0}}(),G=function(){return{send:function(y){for(var b in y)if(y.hasOwnProperty(b)){for(var f=y[b],q=f,m={},e=void 0,B=0;B<q.length;B++)e=q[B].c,m[e]||(m[e]=[]),m[e].push(q[B]);var f=f[0]||{},q=f.sn||a.ue_sn,f=c+(f.m||a.ue_mid)+":"+(f.s||a.ue_sid)+":"+(f.r||n.rid)+(q?":"+q:""),q=[],e=f,B=[],d=void 0;for(d in m)if(m.hasOwnProperty(d))for(var P=0;P<m[d].length;P++){var h=
m[d][P],D=encodeURIComponent((h.cs?C:t)(h.d));B.push({l:D,t:h.t,p:1,c:d,d:h.cs?"c":"j"})}m=B;B=void 0;d="$";for(h=0;h<m.length;){P=m[h];B!=P.c?(e+=d+P.c+"=",d="&",B=P.c):e+=",";var D=e,v=P.d+":",g=P,e=(g.l.match(".{1,"+(p-e.length)+"}[^%]{0,2}")||[])[0]||"";g.l=g.l.substr(e.length);e=D+(v+e+":"+P.t);if(P.l)e+=":"+P.p++ +"_",q.push(e),e=f,d="$",B=0;else if(h++,1!=P.p)for(e+=":"+P.p+"_"+P.p,D=0;D<P.p-1;D++)q[q.length-D-1]+=P.p}q.push(e);f=q;for(q=0;q<f.length;q++)(new Image).src=f[q]}},isSupported:!0}}(),
M=function(){return{send:function(a){for(var b in a)if(a.hasOwnProperty(b)){var f=L.buildPOSTBodyLog(a[b]);if(!navigator.sendBeacon(c,t(f)))throw"";}},isSupported:!!navigator.sendBeacon}}();n._fic=G;n._fac=L;n._fbc=M;n._flq=m;n.sid=n.sid||a.ue_sid;n.mid=n.mid||a.ue_mid;n.furl=n.furl||a.ue_furl;n.sn=n.sn||a.ue_sn;n.isBF=function(){var a=d.performance||d.webkitPerformance,b=w.ue_backdetect&&w.ue_backdetect.ue_back&&document.ue_backdetect.ue_back.value,f=n.bfini;return a&&a.navigation&&2===a.navigation.type||
1<f||!f&&1<b}();try{d.amznJQ&&d.amznJQ.declareAvailable&&d.amznJQ.declareAvailable("forester-client"),d.P&&d.P.register&&d.P.register("forester-client",z)}catch(O){a.ueLogError(O,{logLevel:"WARN"})}(function(){n.log&&n.log.isStub&&(n.log.replay(function(a,b,f){var q=a[2]||{};q.t=b;q.r=f;q.n=1;g(a[0],a[1],q)}),n.onunload.replay(function(a){b.push(a[0])}),n.onflush.replay(function(a){e.push(a[0])}))})();n.log=g;n.log.reset=function(){H=0};n.onunload=function(a){b.push(a)};n.onflush=function(a){e.push(a)};
n.attach("beforeunload",v);n.attach("pagehide",v);r("ld","ue_frst_v2",{wb:1})})(ue_csm,window,document);
(function(a,d){function w(a){if(a)return a.replace(/^\s+|\s+$/g,"")}function l(c,m){if(!c)return{};var b="INFO"===m.logLevel;c.m&&c.m.message&&(c=c.m);var e=m.m||m.message||"",e=c.m&&c.m.message?e+c.m.message:c.m&&c.m.target&&c.m.target.tagName?e+("Error handler invoked by "+c.m.target.tagName+" tag"):c.m?e+c.m:c.message?e+c.message:e+"Unknown error",e={m:e,name:c.name,type:c.type,csm:h+" "+(c.fromOnError?"onerror":"ueLogError")},d,g,p=0,r;e.logLevel=m.logLevel||v;m.adb&&(e.adb=m.adb);if(d=m.attribution)e.attribution=
""+d;if(!b){e.pageURL=m.pageURL||""+(window.location?window.location.href:"")||"missing";e.f=c.f||c.sourceURL||c.fileName||c.filename||c.m&&c.m.target&&c.m.target.src;e.l=c.l||c.line||c.lineno||c.lineNumber;e.c=c.c?""+c.c:c.c;e.s=[];e.t=a.ue.d();if((b=c.stack||(c.err?c.err.stack:""))&&b.split)for(e.csm+=" stack",d=b.split("\n");p<d.length&&e.s.length<z;)(b=d[p++])&&e.s.push(w(b));else for(e.csm+=" callee",g=k(c.args||arguments,"callee"),d=p=0;g&&p<z;)r=t,g.skipTrace||(b=g.toString())&&b.substr&&(r=
0===d?4*t:r,r=1==d?2*t:r,e.s.push(b.substr(0,r)),d++),g=k(g,"caller"),p++;if(!e.f&&0<e.s.length&&(p=e)&&p.s){var l,b=0<p.s.length?p.s[0]:"";d=1<p.s.length?p.s[1]:"";b&&(l=b.match(n));l&&3==l.length||!d||(l=d.match(C));l&&3==l.length&&(p.f=l[1],p.l=l[2])}}return e}function k(a,m){try{return a[m]}catch(b){}}function u(c,m){if(c){var b=l(c,m);a.ue.log(b,m.channel||g,{nb:1});"function"===typeof ue_err.elh&&ue_err.elh(c,m);try{if(!c.fromOnError){var e=d.console,h=d.JSON,n="Error logged with the Track&Report JS errors API(http://tiny/1covqr6l8/wamazindeClieUserJava): ";
if(e){if(h&&h.stringify)try{n+=h.stringify(b)}catch(v){n+="no info provided; converting to string failed"}else n+=b.m;"function"===typeof e.error?e.error(n,b):"function"===typeof e.log&&e.log(n,b)}}}catch(p){}}}function A(c,m){if(c&&!(a.ue_err.ec>a.ue_err.mxe)){a.ue_err.ter.push(c);m=m||{};var b=c.logLevel||m.logLevel;m.logLevel=b;m.attribution=c.attribution||m.attribution;b&&b!==v&&b!==x&&b!==r&&b!==p||a.ue_err.ec++;b&&b!=v||ue_err.ecf++;u(c,m)}}if(!a.ueLogError||a.ueLogError.isStub){var g=a.ue_err_chan||
"jserr",v="FATAL",x="ERROR",r="WARN",p="DOWNGRADED",h="v5",z=20,t=256,C=/\(?([^\s]*):(\d+):\d+\)?/,n=/.*@(.*):(\d*)/;u.skipTrace=1;l.skipTrace=1;A.skipTrace=1;(function(){if(a.ue_err.erl){var c=a.ue_err.erl.length,m,b;for(m=0;m<c;m++)b=a.ue_err.erl[m],u(b.ex,b.info);ue_err.erl=[]}})();a.ueLogError=A}})(ue_csm,window);
(function(a,d){a.ue_cel||(a.ue_cel=function(){function w(a,b){b?b.r=C:b={r:C,c:1};b.clog&&h.clog?h.clog(a,b.ns||x,b):b.glog&&h.glog?h.glog(a,b.ns||x,b):h.log(a,b.ns||x,b)}function l(){var a=g.length;if(0<a){for(var b=[],c=0;c<a;c++){var d=g[c].api;d.ready()?(d.on({ts:h.d,ns:x}),v.push(g[c]),w({k:"mso",n:g[c].name,t:h.d()})):b.push(g[c])}g=b}}function k(){if(!k.executed){for(var a=0;a<v.length;a++)v[a].api.off&&v[a].api.off({ts:h.d,ns:x});u();w({k:"eod",t0:h.t0,t:h.d()},{c:1,il:1});k.executed=1;for(a=
0;a<v.length;a++)g.push(v[a]);v=[];clearTimeout(r);clearTimeout(p)}}function u(){w({k:"hrt",t:h.d()},{c:1,il:1,n:1})}var A=void 0===typeof d.ue_cel_hrt?-1:d.ue_cel_hrt,g=[],v=[],x=a.ue_cel_ns||"cel",r,p,h=a.ue,z=a.uet,t=a.uex,C=h.rid,n=function(){var a=d.performance;return a&&a.navigation&&2===a.navigation.type}(),c=d.requestAnimationFrame||function(a){a()};if(n)w({k:"bft",t:h.d()});else return"function"==typeof z&&z("bb","csmCELLSframework",{wb:1}),setTimeout(l,0),h.onunload(k),r=setTimeout(k,6E5),
0<A&&(p=setInterval(u,A)),"function"==typeof t&&t("ld","csmCELLSframework",{wb:1}),{registerModule:function(a,b){g.push({name:a,api:b});w({k:"mrg",n:a,t:h.d()});l()},reset:function(a){w({k:"rst",t0:h.t0,t:h.d()});g=g.concat(v);v=[];for(var b=g.length,c=0;c<b;c++)g[c].api.off(),g[c].api.reset();C=a||h.rid;l();clearTimeout(r);r=setTimeout(k,6E5);k.executed=0},timeout:function(a,b){return d.setTimeout(function(){c(a)},b)},log:w}}())})(ue_csm,window);
(function(a,d,w){a.ue_pdm||!a.ue_cel||ue.isBF||(a.ue_pdm=function(){function l(){var b={w:g.width,aw:g.availWidth,h:g.height,ah:g.availHeight,cd:g.colorDepth,pd:g.pixelDepth},c={w:(w.body||{}).scrollWidth,h:(w.body||{}).scrollHeight};p&&p.w==b.w&&p.h==b.h&&p.aw==b.aw&&p.ah==b.ah&&p.pd==b.pd&&p.cd==b.cd||(p=b,p.t=x(),p.k="sci",C(p));h&&h.w==c.w&&h.h==c.h||(h=c,h.t=x(),h.k="doi",C(h));v=a.ue_cel.timeout(l,r)}function k(){!1!==z&&C({k:"ebl",t:x()},{ff:1});z=!1}function u(){!0!==z&&C({k:"efo",t:x()});
z=!0}function A(){d.setTimeout(function(){w[e]?k():u()},0)}var g,v,x,r,p,h,z=null,t=a.ue,C=a.ue_cel.log,n=a.uet,c=a.uex,m=1===d.ue_cel_viz&&t.pageViz,b=m&&t.pageViz.event,e=m&&t.pageViz.propHid;"function"==typeof n&&n("bb","csmCELLSpdm",{wb:1});return{on:function(e){r=e.timespan||500;x=e.ts;g=d.screen;t.attach&&(m&&t.attach(b,A,w),t.attach("blur",k,d),t.attach("focus",u,d));e=d.location;C({k:"pmd",o:e.origin,p:e.pathname,t:x()});a.ue_cel.timeout(l,0);"function"==typeof c&&c("ld","csmCELLSpdm",{wb:1})},
off:function(a){clearTimeout(v);t.detach&&(m&&t.detach(b,A,w),t.detach("blur",k,d),t.detach("focus",u,d));t.count&&(t.count("cel.PDM.TotalExecutions",0),t.count("cel.PDM.TotalExecutionTime",0),t.count("cel.PDM.AverageExecutionTime",0/0))},ready:function(){return w.body&&a.ue_cel&&a.ue_cel.log},reset:function(){p=h=null}}}(),a.ue_cel&&a.ue_cel.registerModule("page module",a.ue_pdm))})(ue_csm,window,document);
(function(a,d){a.ue_vpm||!a.ue_cel||ue.isBF||(a.ue_vpm=function(){function w(){var a=g(),c={w:d.innerWidth,h:d.innerHeight,x:d.pageXOffset,y:d.pageYOffset};k&&k.w==c.w&&k.h==c.h&&k.x==c.x&&k.y==c.y||(c.t=a,c.k="vpi",k=c,p(k,{clog:1}));u=0;v=g()-a;x+=1}function l(){u||(u=a.ue_cel.timeout(w,A))}var k,u,A,g,v=0,x=0,r=a.ue,p=a.ue_cel.log,h=a.uet,z=a.uex,t=r.attach,C=r.detach;"function"==typeof h&&h("bb","csmCELLSvpm",{wb:1});return{on:function(d){g=d.ts;A=d.timespan||100;a.ue_cel.timeout(w,0);t&&(t("scroll",
l),t("resize",l));"function"==typeof z&&z("ld","csmCELLSvpm",{wb:1})},off:function(a){clearTimeout(u);C&&(C("scroll",l),C("resize",l));r.count&&(r.count("cel.VPI.TotalExecutions",x),r.count("cel.VPI.TotalExecutionTime",v),r.count("cel.VPI.AverageExecutionTime",v/x))},ready:function(){return a.ue_cel&&a.ue_cel.log},reset:function(){k=void 0},getVpi:function(){return k}}}(),a.ue_cel&&a.ue_cel.registerModule("viewport module",a.ue_vpm))})(ue_csm,window);
(function(a,d,w){if(!a.ue_fem&&a.ue_cel){var l=a.ue||{};!l.isBF&&!a.ue_fem&&w.querySelector&&d.getComputedStyle&&[].forEach&&(a.ue_fem=function(){function k(a,f){return a>f?3>a-f:3>f-a}function u(a,f){var q=d.pageXOffset,b=d.pageYOffset,y;a:{try{if(a){var c=a.getBoundingClientRect();y={x:c.left+q|0,y:c.top+b|0,w:c.width|0,h:c.height|0,d:(0===a.offsetWidth&&0===a.offsetHeight)|0}}else y=void 0;break a}catch(e){}y=void 0}if(y&&!a.cel_b)a.cel_b=y,m({n:a.cel_n,w:a.cel_b.w,h:a.cel_b.h,d:a.cel_b.d,x:a.cel_b.x,
y:a.cel_b.y,t:f,k:"ewi",cl:a.className},{clog:1});else{if(q=y)q=a.cel_b,b=y,q=b.d===q.d&&1===b.d?!1:!(k(q.x,b.x)&&k(q.y,b.y)&&k(q.w,b.w)&&k(q.h,b.h)&&q.d===b.d);q&&(a.cel_b=y,m({n:a.cel_n,w:a.cel_b.w,h:a.cel_b.h,d:a.cel_b.d,x:a.cel_b.x,y:a.cel_b.y,t:f,k:"ewi"},{clog:1}))}}function A(a,q){var b;b=a.c?w.getElementsByClassName(a.c):a.id?[w.getElementById(a.id)]:w.querySelectorAll(a.s);a.w=[];for(widgetIndex=0;widgetIndex<b.length;widgetIndex++){var y=b[widgetIndex];y&&(y.cel_n||(y.cel_n=y.getAttribute("cel_widget_id")||
(a.id_gen||c)(y,widgetIndex)||y.id),a.w.push(y),x(f,y,q))}}function g(a,f){b.contains(a)||m({n:a.cel_n,t:f,k:"ewd"},{clog:1})}function v(a){G.length&&ue_cel.timeout(function(){for(var f=S(),b=!1;S()-f<t&&!b;){for(b=O;0<b--&&0<G.length;){var y=G.shift();q[y.type](y.elem,y.time)}b=0===G.length}M++;v(a)},0)}function x(a,f,q){G.push({type:a,elem:f,time:q})}function r(a,f){for(var q=0;q<n.length;q++)for(var b=n[q].w||[],y=0;y<b.length;y++)x(a,b[y],f)}function p(){L||(L=a.ue_cel.timeout(function(){L=null;
var a=C();r(y,a);for(var f=0;f<n.length;f++)x(Q,n[f],a);v(a)},z))}function h(){L||H||(H=a.ue_cel.timeout(function(){H=null;var a=C();r(f,a);v(a)},z))}var z=50,t=4.5,C,n=[],c=function(){},m=a.ue_cel.log,b,e,D,F,I=d.MutationObserver||d.WebKitMutationObserver||d.MozMutationObserver,N=!!I,J,K,H,L,G=[],M=0,O=null,y="removedWidget",Q="updateWidgets",f="processWidget",q,R=d.performance||{},S=R.now&&function(){return R.now()}||function(){return Date.now()};"function"==typeof uet&&uet("bb","csmCELLSfem",{wb:1});
return{on:function(f){function y(){if(D&&F&&b&&b.contains&&b.getBoundingClientRect&&C){q={removedWidget:g,updateWidgets:A,processWidget:u};if(N){var a={attributes:!0,subtree:!0};J=new I(h);K=new I(p);J.observe(b,a);K.observe(b,{childList:!0,subtree:!0});K.observe(e,a)}else D.call(b,"DOMAttrModified",h),D.call(b,"DOMNodeInserted",p),D.call(b,"DOMNodeRemoved",p),D.call(e,"DOMNodeInserted",h),D.call(e,"DOMNodeRemoved",h);p()}}b=w.body;e=w.head;D=b.addEventListener;F=b.removeEventListener;C=f.ts;n=a.cel_widgets||
[];O=f.bs||5;l.deffered?y():l.attach&&l.attach("load",y);"function"==typeof uex&&uex("ld","csmCELLSfem",{wb:1})},off:function(){D&&F&&b&&b.contains&&b.getBoundingClientRect&&C&&(K&&(K.disconnect(),K=null),J&&(J.disconnect(),J=null),F.call(b,"DOMAttrModified",h),F.call(b,"DOMNodeInserted",p),F.call(b,"DOMNodeRemoved",p),F.call(e,"DOMNodeInserted",h),F.call(e,"DOMNodeRemoved",h));l.count&&l.count("cel.widgets.batchesProcessed",M)},ready:function(){return a.ue_cel&&a.ue_cel.log},reset:function(){n=a.cel_widgets||
[]}}}(),a.ue_cel&&a.ue_fem&&a.ue_cel.registerModule("features module",a.ue_fem))}})(ue_csm,window,document);
(function(a,d){a.ue_mcm||!a.ue_cel||a.ue.isBF||(a.ue_mcm=function(){function w(a){try{if(a.id)return"//*[@id='"+a.id+"']";var d,g=1,p;for(p=a.previousSibling;p;p=p.previousSibling)p.nodeName==a.nodeName&&(g+=1);d=g;var h=a.nodeName;1!=d&&(h+="["+d+"]");a.parentNode&&(h=w(a.parentNode)+"/"+h);return h}catch(k){return"DETACHED"}}function l(a,l){var r=a.srcElement||a.target||{},p={k:k,w:(l||{}).ow||(d.body||{}).scrollWidth,h:(l||{}).oh||(d.body||{}).scrollHeight,t:(l||{}).ots||u(),x:a.pageX,y:a.pageY,
p:w(r),n:r.nodeName};a.button&&(p.b=a.button);r.href&&(p.r=r.href);r.id&&(p.i=r.id);r.className&&r.className.split&&(p.c=r.className.split(/\s+/));g(p,{c:1})}var k="mcm",u,A=a.ue,g=a.ue_cel.log;return{on:function(g){u=g.ts;a.ue_cel_stub&&a.ue_cel_stub.replayModule(k,l);A.attach&&A.attach("click",l,d)},off:function(a){A.detach&&A.detach("click",l,d)},ready:function(){return a.ue_cel&&a.ue_cel.log},reset:function(){}}}(),a.ue_cel&&a.ue_cel.registerModule("mouse click module",a.ue_mcm))})(ue_csm,document);
(function(a,d){a.ue_mmm||!a.ue_cel||a.ue.isBF||(a.ue_mmm=function(w){function l(a,b){var c={x:a.pageX||a.x||0,y:a.pageY||a.y||0,t:x()};!b&&I&&(c.t-I.t<A||c.x==I.x&&c.y==I.y)||(I=c,e.push(c))}function k(){if(e.length){m=H.now();for(var a=0;a<e.length;a++){var d=e[a],p=a;N=e[F];J=d;var k=void 0;if(!(k=2>p)){a:if(e[p].t-e[p-1].t>u)k=0;else{for(k=F+1;k<p;k++){var y=N,Q=J,f=e[k];K=(Q.x-y.x)*(y.y-f.y)-(y.x-f.x)*(Q.y-y.y);if(K*K/((Q.x-y.x)*(Q.x-y.x)+(Q.y-y.y)*(Q.y-y.y))>g){k=0;break a}}k=1}k=!k}k?F=p-1:
D.pop();D.push(d)}b=H.now()-m;t=Math.min(t,b);C=Math.max(C,b);n=(n*c+b)/(c+1);c+=1;h({k:v,e:D,min:Math.floor(1E3*t),max:Math.floor(1E3*C),avg:Math.floor(1E3*n)},{c:1});e=[];D=[];F=0}}var u=100,A=20,g=25,v="mmm1",x,r,p=a.ue,h=a.ue_cel.log,z,t=1E3,C=0,n=0,c=0,m,b,e=[],D=[],F=0,I,N,J,K,H=w&&w.now&&w||Date.now&&Date||{now:function(){return(new Date).getTime()}};return{on:function(a){x=a.ts;r=a.ns;p.attach&&p.attach("mousemove",l,d);z=setInterval(k,3E3)},off:function(a){r&&(I&&l(I,!0),k());clearInterval(z);
p.detach&&p.detach("mousemove",l,d)},ready:function(){return a.ue_cel&&a.ue_cel.log},reset:function(){e=[];D=[];F=0;I=null}}}(window.performance),a.ue_cel&&a.ue_cel.registerModule("mouse move module",a.ue_mmm))})(ue_csm,document);